### ISSUE TITLE
brew install z80oolong/tmux/powerline-statusでpkg_resources.DistributionNotFoundが発生

### ISSUE THREAD

**Issue by Onooono** [z80oolong/homebrew-tmux#3]
以下のエラーが発生しています。
申し訳ありませんが、pythonはよく分からず、当方の環境によるエラーなのかが判断できておりません。

まずは入力したコマンドと標準出力の内容です。

> $ brew install z80oolong/tmux/powerline-status
> ==> Installing powerline-status from z80oolong/tmux
> ==> Downloading https://files.pythonhosted.org/packages/06/8c/eb8a0ae49eba5be054ca32b3a1dca432baee1d83c4f125d276c6a5fd2d20/virtualenv-20.1.0.tar.gz
> Already downloaded: /home/onoo/.cache/Homebrew/downloads/b4e86049c816dde47c7a914a6db0f94a5688cb385de88d3bb08edd041e561aa6--virtualenv-20.1.0.tar.gz
> ==> Downloading https://files.pythonhosted.org/packages/d7/d8/05696357e0311f5b5c316d7b95f46c669dd9c15aaeecbb48c7d0aeb88c40/appdirs-1.4.4.tar.gz
> Already downloaded: /home/onoo/.cache/Homebrew/downloads/d46628d315f103ea527907020cf5f6c94365bbb549783f75a794526482afb672--appdirs-1.4.4.tar.gz
> ==> Downloading https://files.pythonhosted.org/packages/2f/83/1eba07997b8ba58d92b3e51445d5bf36f9fba9cb8166bcae99b9c3464841/distlib-0.3.1.zip
> Already downloaded: /home/onoo/.cache/Homebrew/downloads/b25916e85753e80fccf86f2f1ba088b86d1a82c93cd36bdb72613c81cb830c55--distlib-0.3.1.zip
> ==> Downloading https://files.pythonhosted.org/packages/14/ec/6ee2168387ce0154632f856d5cc5592328e9cf93127c5c9aeca92c8c16cb/filelock-3.0.12.tar.gz
> Already downloaded: /home/onoo/.cache/Homebrew/downloads/6132211d03cc3113b135a5b72510e3b6ea1df5bf527eb89d71c3f45085c252a7--filelock-3.0.12.tar.gz
> ==> Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
> Already downloaded: /home/onoo/.cache/Homebrew/downloads/e99698a932bde9f5fb8ca552923ae339984f284e1c7764df95c12175f573c0d7--six-1.15.0.tar.gz
> ==> Downloading https://github.com/powerline/powerline/archive/2.7.tar.gz
> Already downloaded: /home/onoo/.cache/Homebrew/downloads/ea0571b921a807c14141d2f76c214a3d1cc07b0f8bf2d352e503d2a0efe9707f--powerline-2.7.tar.gz
> ==> Patching
> ==> python2 -c import setuptools... --no-user-cfg install --prefix=/tmp/powerline-status--homebrew-virtualenv-20201204-32181-124r9tj/target/vendor --install-scripts=/tmp/powerline-status--homebrew-virtualenv-20201204-32181-124r9
> ==> python2 -c import setuptools... --no-user-cfg install --prefix=/tmp/powerline-status--homebrew-virtualenv-20201204-32181-124r9tj/target/vendor --install-scripts=/tmp/powerline-status--homebrew-virtualenv-20201204-32181-124r9
> ==> python2 -c import setuptools... --no-user-cfg install --prefix=/tmp/powerline-status--homebrew-virtualenv-20201204-32181-124r9tj/target/vendor --install-scripts=/tmp/powerline-status--homebrew-virtualenv-20201204-32181-124r9
> ==> python2 -c import setuptools... --no-user-cfg install --prefix=/tmp/powerline-status--homebrew-virtualenv-20201204-32181-124r9tj/target/vendor --install-scripts=/tmp/powerline-status--homebrew-virtualenv-20201204-32181-124r9
> ==> python2 -c import setuptools... --no-user-cfg install --prefix=/tmp/powerline-status--homebrew-virtualenv-20201204-32181-124r9tj/target --install-scripts=/tmp/powerline-status--homebrew-virtualenv-20201204-32181-124r9tj/targ
> ==> python2 -s /tmp/powerline-status--homebrew-virtualenv-20201204-32181-124r9tj/target/bin/virtualenv -p python2 /home/onoo/.linuxbrew/Cellar/powerline-status/2.7/libexec
> 

ここでエラーが発生しています。
エラー内容は以下です。

> 2020-12-04 16:10:19 +0900
> 
> python2
> -s
> /tmp/powerline-status--homebrew-virtualenv-20201204-1550-14m8o2i/target/bin/virtualenv
> -p
> python2
> /home/onoo/.linuxbrew/Cellar/powerline-status/2.7/libexec
> 
> Traceback (most recent call last):
>   File "/tmp/powerline-status--homebrew-virtualenv-20201204-1550-14m8o2i/target/bin/virtualenv", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/home/onoo/.linuxbrew/opt/python@2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
>     @_call_aside
>   File "/home/onoo/.linuxbrew/opt/python@2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
>     f(*args, **kwargs)
>   File "/home/onoo/.linuxbrew/opt/python@2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/home/onoo/.linuxbrew/opt/python@2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
>     ws.require(__requires__)
>   File "/home/onoo/.linuxbrew/opt/python@2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/home/onoo/.linuxbrew/opt/python@2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'importlib-metadata<3,>=0.12' distribution was not found and is required by virtualenv

tmuxでEAWの問題解決を探っていて貴方のパッチにたどり着きました。
解決できると非常にありがたいです。

**Comment by z80oolong** [comment]
@Onooono 様：

この度は本リポジトリを御利用頂き、誠に有難う御座います。

本リポジトリ同梱の z80oolong/tmux/powerline-status によって導入される powerline が古いバージョンのものでありましたので、最新の powerline 2.8.1 が導入されるように当該 Formula を修正致しました。

どうか御確認下さい。
